#!/usr/bin/env bun

const subprocess1 = Bun.spawn(["pnpm", "nx", "run-many", "-t=build"], {
  stdio: ["ignore", "inherit", "inherit"],
});
if ((await subprocess1.exited) !== 0) {
  process.exit(1);
}

const preFile = Bun.file(".changeset/pre.json");
const tag =
  ((await preFile.exists()) && (await preFile.json()).tag) || "latest";

const subprocess2 = Bun.spawn(
  [
    "pnpm",
    "nx",
    "release",
    "publish",
    `--tag=${tag}`,
    ...process.argv.slice(2),
  ],
  {
    stdio: ["ignore", "inherit", "inherit"],
  },
);
if ((await subprocess2.exited) !== 0) {
  process.exit(1);
}
