#!/usr/bin/env bun
import { cpus } from "node:os";

const subprocess = Bun.spawn(
  [
    "pnpm",
    "exec",
    "nx",
    "run-many",
    "--parallel",
    String(cpus().length),
    "-t",
    ...process.argv.slice(2),
  ],
  {
    stdio: ["inherit", "inherit", "inherit"],
  },
);

process.exit(await subprocess.exited);
